source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/BJComponent/BJSpecs.git'

use_frameworks!

platform :ios, '8.0'

target 'FFAuthorKit_Example' do
  pod 'FFAuthorKit', :path => '../'
  
  pod 'Masonry'
  pod 'YYWebImage'
  pod 'ReactiveCocoa', '~> 2.5'

  pod 'FFAPIs', '~> 0.1.1'
  pod 'FFReformerKeysKit', '~> 0.1.0'
  pod 'FFMainViewKit', '~> 0.1.0'
  pod 'FFCategoryKit', '~> 0.1.1'
  pod 'FFToolsKit', '~> 0.1.0'
  pod 'FFConfigsKit', '~> 0.1.0'

  target 'FFAuthorKit_Tests' do
    inherit! :search_paths

    
  end
end
