source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/BJComponent/BJSpecs.git'

use_frameworks!

platform :ios, '8.0'

target 'FFAuthorKit_Example' do
  pod 'FFAuthorKit', :path => '../'
  
  pod 'Masonry'
  pod 'YYWebImage'

  pod 'FFAPIs', '~> 0.1.4'
  pod 'FFUtils', '~> 0.1.5'
  pod 'FFWdiget', '~> 0.1.1'
  
  pod 'FFSpecialKit_Category'

  target 'FFAuthorKit_Tests' do
    inherit! :search_paths

    
  end
end
